name: casha
description: A simple cash denomination breakdown system.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3

flutter:
  uses-material-design: true
